parameters:
    ezplatform.http_cache.proxy_client.varnish.class: EzSystems\PlatformHttpCacheBundle\ProxyClient\Varnish

services:
    ezplatform.http_cache.cache_manager:
        parent: fos_http_cache.cache_manager
        class: FOS\HttpCacheBundle\CacheManager

    ezplatform.http_cache.proxy_client.varnish.factory:
        class: EzSystems\PlatformHttpCacheBundle\PurgeClient\VarnishProxyClientFactory
        arguments: ['@ezpublish.config.resolver', '@ezpublish.config.dynamic_setting.parser', '%ezplatform.http_cache.proxy_client.varnish.class%']

    ezplatform.http_cache.purge_client:
        alias: ezplatform.http_cache.purge_client_decorator

    ezplatform.http_cache.purge_client_decorator:
        class: EzSystems\PlatformHttpCacheBundle\PurgeClient\RepositoryPrefixDecorator
        arguments: ['@ezplatform.http_cache.purge_client_internal']
        # Use setter to avoid SiteAccess system creating two instances of handler before and after SiteAccess is set
        calls:
            - [setRepositoryId, [$repository$]]

    ezplatform.http_cache.purge_client_internal:
        alias: ezplatform.http_cache.purge_client.local

    ezplatform.http_cache.purge_client.varnish:
        class: EzSystems\PlatformHttpCacheBundle\PurgeClient\VarnishPurgeClient
        arguments:
            - '@ezplatform.http_cache.cache_manager'
            - '@ezpublish.config.resolver'
        tags:
            - {name: ezplatform.http_cache.purge_client, purge_type: http}
            - {name: ezplatform.http_cache.purge_client, purge_type: varnish}

    ezplatform.http_cache.purge_client.local:
        class: EzSystems\PlatformHttpCacheBundle\PurgeClient\LocalPurgeClient
        arguments: ['@ezplatform.http_cache.store']
        tags:
            - {name: ezplatform.http_cache.purge_client, purge_type: local}

    ezplatform.http_cache.store:
        alias: ezplatform.http_cache.tag_aware_store

    ezplatform.http_cache.tag_aware_store:
        class: EzSystems\PlatformHttpCacheBundle\Proxy\TagAwareStore
        arguments: ['%ezplatform.http_cache.store.root%']

    ezplatform.http_cache.fos_tag_handler.xkey:
        class: EzSystems\PlatformHttpCacheBundle\Handler\TagHandler
        arguments:
         - '@ezplatform.http_cache.cache_manager'
         - '%ezplatform.http_cache.tags.header%'
         - '@ezplatform.http_cache.purge_client'
        # Use setter to avoid SiteAccess system creating two instances of handler before and after SiteAccess is set
        calls:
            - [setRepositoryId, [$repository$]]

    ezplatform.http_cache.user_context_provider.role_identify:
        class: EzSystems\PlatformHttpCacheBundle\ContextProvider\RoleIdentify
        arguments: ["@ezpublish.api.repository"]
        tags:
            - { name: fos_http_cache.user_context_provider }
